### ISSUE TITLE
Pan and shower are not usable

### ISSUE THREAD

**Issue by adilaxmdv** [noyainrain/feini#5]
i cant use 🚿 ,🍳 but i have in tent . When i use it(🚿,🍳) say :**You have no 🚿 at the moment. Maybe have a look in the tent ⛺️?**

**Comment by noyainrain** [comment]
Thank you very much for the report! I can confirm this is a bug and we will fix it soon. :blush:

If you're interested in helping out with the fix, I'm happy to answer any questions that might come up. :blush:

**Comment by noyainrain** [comment]
Here is a draft for the missing functionality:

```python
class Space:
    async def cook(self) -> str:
        """Prepare a dish from a vegetable."""
```

```
🍳
Prepare a dish.

🧽
🚿
Wash the pet. The shower evokes a 😍 reaction.
```

Depends on #9 .

**Comment by noyainrain** [comment]
Tasks:

* [x] Implement draft
* [x] Move relevant attributes from `Space` to `Pet`
* [x] `update_pet_name()`
* [x] Add `space-fix-pan` and `space-fix-shower` events
